version: 2
jobs:
    build_py3:
        working_directory: ~/mcQA
        docker:
            - image: tayciryahmed/nlp
        resource_class: large
        parallelism: 4
        steps:
            - checkout
            - run: python -m pytest -sv ./mcqa/tests/ --cov
            - run: codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3