version: 2
jobs:
    build_py3:
        working_directory: ~/mcQA
        docker:
            - image: tayciryahmed/nlp:v0.0.2
        resource_class: medium
        parallelism: 4
        steps:
            - checkout
            - run: pip install transformers==2.10.0 codecov  --user
            - run: python -m pytest -sv ./mcqa/tests/ --cov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3
