version: 2
jobs:
    build_py3:
        working_directory: ~/mcQA
        docker:
            - image: circleci/python:3.5
        resource_class: large
        parallelism: 4
        steps:
            - checkout
            - run: sudo pip install --progress-bar off .
            - run: sudo pip install pytest codecov pytest-cov
            - run: sudo pip install tensorboardX scikit-learn
            - run: sudo pip install pytorch-transformers
            - run: git clone https://www.github.com/nvidia/apex && cd apex && sudo python setup.py install && cd ..
            - run: python -m pytest -sv ./mcqa/tests/ --cov
            - run: codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3